version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: cheapcc-ollama
    ports:
      - '11434:11434'
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_ORIGINS=*
      - OLLAMA_HOST=0.0.0.0
    restart: unless-stopped
    networks:
      - n8n-network

volumes:
  ollama_data:
    driver: local

networks:
  n8n-network:
    external: true
    # If n8n network doesn't exist, create it with:
    # docker network create n8n-network
