import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Adobe Creative Cloud Discount - Student, Teacher & Military Pricing | CheapCC',
  description: 'Get Adobe Creative Cloud discount with student, teacher, and military pricing. Pre-activated accounts, email-activation, and redemption codes available. Save up to 83% on Adobe CC.',
  keywords: [
    'adobe creative cloud discount',
    'adobe creative cloud student discount',
    'adobe creative cloud teacher discount',
    'adobe creative cloud education discount',
    'adobe creative cloud military discount',
    'adobe creative cloud pricing',
    'adobe creative cloud cost',
    'adobe creative cloud price',
    'adobe creative cloud subscription',
    'adobe creative cloud all apps',
    'adobe creative cloud alternatives',
    'cheap adobe creative cloud',
    'adobe creative cloud cheap',
    'adobe creative cloud student',
    'adobe creative cloud for students',
    'adobe creative cloud education',
    'adobe creative cloud membership',
    'adobe creative cloud subscription plans',
    'adobe creative cloud student pricing',
    'adobe creative cloud student plan',
    'adobe creative cloud student rate',
    'adobe creative cloud student deal',
    'adobe creative cloud for students price',
    'adobe creative cloud student cost',
    'adobe creative cloud all apps subscription',
    'adobe creative cloud discounts',
    'adobe creative cloud price increase',
    'adobe creative cloud all apps price',
    'adobe creative cloud annual subscription',
    'adobe creative cloud yearly subscription',
    'adobe creative cloud monthly cost',
    'adobe creative cloud suite price',
    'adobe creative cloud subscriptions',
    'adobe creative cloud cancel subscription',
    'adobe creative cloud cancel',
    'adobe creative cloud cancellation',
    'adobe creative cloud cancel account',
    'adobe creative cloud end subscription',
    'adobe creative cloud subscription cancel',
    'adobe creative cloud studenten',
    'adobe creative cloud for student',
    'adobe creative cloud all apps student discount',
    'adobe creative cloud discount coupon',
    'adobe creative cloud alternative download',
    'best adobe creative cloud alternatives',
    'cheaper alternatives to adobe creative cloud',
    'cheapest adobe creative cloud country',
    'cheapest country for adobe creative cloud',
    'cheapest way to get adobe creative cloud',
    'adobe creative cloud 1 year cheap',
    'adobe creative cloud buy cheap',
    'adobe creative cloud cheap price',
    'adobe creative cloud cheap reddit',
    'adobe creative cloud cheap subscription',
    'adobe creative cloud cheapest country',
    'adobe creative cloud cheapest price',
    'adobe creative cloud for cheap',
    'cheap adobe creative cloud subscription',
    'pre-activated adobe cc',
    'email-activated adobe cc',
    'adobe creative cloud redemption codes',
    'adobe creative suite deals',
    'adobe cc comparison',
    'adobe creative cloud options'
  ],
  authors: [{ name: 'CheapCC Team' }],
  creator: 'CheapCC',
  publisher: 'CheapCC',
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  metadataBase: new URL('https://cheapcc.net'),
  alternates: {
    canonical: '/adobe-creative-cloud',
  },
  openGraph: {
    title: 'Adobe Creative Cloud Discount - Student, Teacher & Military Pricing | CheapCC',
    description: 'Get Adobe Creative Cloud discount with student, teacher, and military pricing. Pre-activated accounts, email-activation, and redemption codes available. Save up to 83% on Adobe CC.',
    url: 'https://cheapcc.net/adobe-creative-cloud',
    siteName: 'CheapCC',
    images: [
      {
        url: '/og-image.svg',
        width: 1200,
        height: 630,
        alt: 'Adobe Creative Cloud Discount - Student, Teacher & Military Pricing',
      },
    ],
    locale: 'en_US',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Adobe Creative Cloud Discount - Student, Teacher & Military Pricing | CheapCC',
    description: 'Get Adobe Creative Cloud discount with student, teacher, and military pricing. Save up to 83% on Adobe CC with all apps included.',
    images: ['/twitter-image.svg'],
    creator: '@cheapcc',
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
  verification: {
    google: process.env.GOOGLE_SITE_VERIFICATION,
  },
  category: 'technology',
  classification: 'Adobe Creative Cloud, Software, Design Tools, Solutions',
  other: {
    'apple-mobile-web-app-capable': 'yes',
    'apple-mobile-web-app-status-bar-style': 'black-translucent',
    'apple-mobile-web-app-title': 'CheapCC - Adobe Creative Cloud Solutions',
    'application-name': 'CheapCC',
    'msapplication-TileColor': '#ff33ff',
    'theme-color': '#ff33ff',
  },
};

export default metadata;
