// Common geographical regions for specific IP ranges
export const IP_REGIONS: Record<string, { country: string; city?: string }> = {
  '192.168.': { country: 'Local Network', city: 'Private IP' },
  '10.': { country: 'Local Network', city: 'Private IP' },
  '127.': { country: 'Local Network', city: 'Localhost' },
  '::1': { country: 'Local Network', city: 'Localhost' },
  '172.16.': { country: 'Local Network', city: 'Private IP' },
  '172.17.': { country: 'Local Network', city: 'Private IP' },
  '172.18.': { country: 'Local Network', city: 'Private IP' },
  '172.19.': { country: 'Local Network', city: 'Private IP' },
  '172.20.': { country: 'Local Network', city: 'Private IP' },
  '172.21.': { country: 'Local Network', city: 'Private IP' },
  '172.22.': { country: 'Local Network', city: 'Private IP' },
  '172.23.': { country: 'Local Network', city: 'Private IP' },
  '172.24.': { country: 'Local Network', city: 'Private IP' },
  '172.25.': { country: 'Local Network', city: 'Private IP' },
  '172.26.': { country: 'Local Network', city: 'Private IP' },
  '172.27.': { country: 'Local Network', city: 'Private IP' },
  '172.28.': { country: 'Local Network', city: 'Private IP' },
  '172.29.': { country: 'Local Network', city: 'Private IP' },
  '172.30.': { country: 'Local Network', city: 'Private IP' },
  '172.31.': { country: 'Local Network', city: 'Private IP' },
};

// Specific IPs from the screenshot
export const SPECIFIC_IPS: Record<string, { country: string; city?: string }> = {
  '206.223.183.20': { country: 'United States', city: 'Los Angeles' },
  '54.219.120.34': { country: 'United States', city: 'California' },
  '149.88.98.89': { country: 'Germany', city: 'Frankfurt' },
  '37.19.220.88': { country: 'Sweden', city: 'Stockholm' },
  '34.9.44.194': { country: 'Australia', city: 'Sydney' },
  '185.128.135.10': { country: 'Netherlands', city: 'Amsterdam' },
  '123.6.49.14': { country: 'China', city: 'Beijing' },
  '172.70.243.148': { country: 'United States', city: 'San Francisco' },
  '172.69.50.179': { country: 'United States', city: 'San Francisco' },
  '172.71.148.64': { country: 'United States', city: 'San Francisco' },
  '172.71.184.205': { country: 'United States', city: 'San Francisco' },
  '172.70.251.221': { country: 'United States', city: 'San Francisco' },
  '172.69.50.182': { country: 'United States', city: 'San Francisco' },
  '162.158.94.182': { country: 'United States', city: 'San Francisco' },
  '172.68.194.220': { country: 'United States', city: 'San Francisco' },
  '172.68.10.92': { country: 'United States', city: 'San Francisco' },
  '123.6.49.4': { country: 'China', city: 'Beijing' },
  '123.6.49.10': { country: 'China', city: 'Beijing' },
  '123.6.49.41': { country: 'China', city: 'Beijing' },
  '::1': { country: 'Local Network', city: 'Localhost' },
};

// Cloud provider IP ranges (simplified for common ranges)
export const CLOUD_PROVIDERS: Record<string, { provider: string, region?: string }> = {
  '13.': { provider: 'AWS', region: 'Global' },
  '18.': { provider: 'AWS', region: 'Global' },
  '35.': { provider: 'Google Cloud', region: 'Global' },
  '34.9.': { provider: 'Google Cloud', region: 'Asia Pacific' },
  '34.': { provider: 'Google Cloud', region: 'Global' },
  '104.': { provider: 'Microsoft Azure', region: 'Global' },
  '40.': { provider: 'Microsoft Azure', region: 'Global' },
  '52.': { provider: 'AWS', region: 'Global' },
  '54.': { provider: 'AWS', region: 'Global' },
  '149.88.': { provider: 'Hetzner', region: 'Germany' },
  '162.158.': { provider: 'Cloudflare', region: 'Global' },
  '172.68.': { provider: 'Cloudflare', region: 'United States' },
  '172.69.': { provider: 'Cloudflare', region: 'United States' },
  '172.70.': { provider: 'Cloudflare', region: 'United States' },
  '172.71.': { provider: 'Cloudflare', region: 'United States' },
  '123.6.': { provider: 'China Telecom', region: 'China' },
  '37.19.': { provider: 'Telia', region: 'Sweden' },
  '185.128.': { provider: 'Akamai', region: 'Europe' },
};

// Specific country codes for known IP ranges (very simplified)
export const COUNTRY_CODES: Record<string, { country: string, region?: string }> = {
  '1.': { country: 'China/Australia/Japan', region: 'Asia-Pacific' },
  '2.': { country: 'Africa/Europe', region: 'Various' },
  '5.': { country: 'Europe', region: 'Various' },
  '31.': { country: 'United Kingdom', region: 'Europe' },
  '46.': { country: 'Europe', region: 'Various' },
  '62.': { country: 'Europe', region: 'Various' },
  '66.': { country: 'United States', region: 'North America' },
  '69.': { country: 'United States', region: 'North America' },
  '72.': { country: 'United States', region: 'North America' },
  '74.': { country: 'United States', region: 'North America' },
  '76.': { country: 'United States', region: 'North America' },
  '96.': { country: 'United States', region: 'North America' },
  '108.': { country: 'United States', region: 'North America' },
  '123.': { country: 'China', region: 'Asia' },
  '149.': { country: 'Germany', region: 'Europe' },
  '162.': { country: 'United States', region: 'North America' },
  '172.68.': { country: 'United States', region: 'North America' },
  '172.69.': { country: 'United States', region: 'North America' },
  '172.70.': { country: 'United States', region: 'North America' },
  '172.71.': { country: 'United States', region: 'North America' },
  '173.': { country: 'United States', region: 'North America' },
  '174.': { country: 'United States', region: 'North America' },
  '184.': { country: 'United States', region: 'North America' },
  '185.': { country: 'Europe', region: 'Various' },
  '206.': { country: 'United States', region: 'North America' },
  '216.': { country: 'United States', region: 'North America' },
}; 